### PR TITLE
small improvements - https, canPlay maybe, playlist reload

### PR DESCRIPTION
**Pull request by ciAnd7**
Hi,

Here is small fixes witch we have to do to use HLS player on our project.

Thanks.

### CODE REVIEW

**Comment by bbert** [comment]
Hi,
I do not understand the fix for M3U manifest refresh.
If I well understand your commit, you update the current sequence number to the first sequence number of the refreshed playlist. 
Therefore you may download a chunk that is prior (in time) to the already buffered chunks.

**Comment by ciAnd7** [comment]
Hi,

Perhaps, it is necessary to compare/check currentRepresentation.startNumber with current currentSequenceNumber before assign...

The main motivation for patch was to  prevent endless loop when current segment disappeared from refreshed playlist. For example, short playlists (2-3 items) with short segments (2-3 sec) on network or client processing delay.

**Comment by bbert** [comment]
Hi,
Can you update this PR since some corrections have already been pushed into base.
Thanks.

**Comment by ciAnd7** [comment]
Sure. 
ASAP I plan to close it, merge my development branch with yours, and  than creates new PR(s) if needed.

**Pull request closed without merging**
